export function motion(age, startY=0, startScale=1) {
  if (age >= 900) return { malletY: 0, fishScale: 1, wave: 1 };
  if (age < 55) {const u=Math.max(0,age)/55;return {malletY:startY+(68-startY)*u*u,fishScale:startScale+(1-startScale)*u,wave:1};}
  const t = (age-55) / 1000;
  return { malletY: 68 * Math.exp(-8*t) * Math.cos(16*t),
    fishScale: 1 - .026 * Math.exp(-10*t) * Math.cos(23*t), wave: Math.min(t/.85, 1) };
}

export async function loadLayer(name, signal) {
  const response = await fetch(`/instruments/wooden-fish/wooden_fish_${name}.bin`, { signal });
  if (!response.ok) throw new Error("木鱼图层未加载，请重新打开预览");
  const data = new DataView(await response.arrayBuffer());
  const width = data.getUint16(0, true), height = data.getUint16(2, true);
  if (!width || !height || width*height > 120000 || data.byteLength !== 4+width*height*3) throw new Error("木鱼图层损坏");
  const canvas = document.createElement("canvas"); canvas.width=width; canvas.height=height;
  const ctx=canvas.getContext("2d"), image=ctx.createImageData(width,height);
  for(let i=0;i<width*height;i++) {
    const p=data.getUint16(4+i*3,true);
    image.data.set([(p>>11)*255/31,((p>>5)&63)*255/63,(p&31)*255/31,data.getUint8(6+i*3)],i*4);
  }
  ctx.putImageData(image,0,0);return canvas;
}

export function paint(ctx, body, mallet, age, startY=0, startScale=1) {
  const m=motion(age,startY,startScale);ctx.fillStyle="#f1e3cf";ctx.fillRect(0,0,640,480);
  ctx.fillStyle="#54422f";ctx.font='600 27px "PingFang SC", "Microsoft YaHei", sans-serif';ctx.fillText("敲木鱼",30,53);
  ctx.fillStyle="#8b7354";ctx.font='15px "PingFang SC", sans-serif';ctx.fillText("一声木响，一刻安静",31,85);
  if(m.wave<1) {
    ctx.strokeStyle=`rgba(196,159,104,${(1-m.wave)*.45})`;ctx.lineWidth=2;
    ctx.beginPath();ctx.ellipse(316,356,160+m.wave*110,49+m.wave*37,0,0,Math.PI*2);ctx.stroke();
  }
  ctx.fillStyle="#dac3a1";ctx.beginPath();ctx.ellipse(308,410,175,15,0,0,Math.PI*2);ctx.fill();
  if(body)ctx.drawImage(body,110,425-297*m.fishScale,390*m.fishScale,297*m.fishScale);
  if(mallet)ctx.drawImage(mallet,340,85+m.malletY,210,214);
  ctx.fillStyle="#8b7354";ctx.font='15px "PingFang SC", sans-serif';ctx.textAlign="center";
  ctx.fillText("按主操作敲一下 · 全局键退出",320,464);ctx.textAlign="left";
}

/* Browser audition uses the exact PCM generated by the portable firmware DSP.
 * An AudioContext is created only in a user gesture; unmount/blur closes it. */
export class WoodenFishAudio {
  constructor() { this.context=null;this.voices=[];this.disposed=false; }
  async prepare() {
    if(this.disposed)return;
    if(!this.context) {
      this.context=new AudioContext();
      const context=this.context;
      this.ready=Promise.all(["knock","ambience"].map(async name=>{
        const r=await fetch(`/instruments/wooden-fish/${name}.wav?v=4`);
        if(!r.ok)throw new Error("预览声音未加载");
        return context.decodeAudioData(await r.arrayBuffer());
      })).then(([knock,ambience])=>{this.knock=knock;this.ambience=ambience;});
    }
    const context=this.context;
    await context.resume();await this.ready;
  }
  async strike() {
    await this.prepare();if(this.disposed)return false;
    const c=this.context;
    if(!this.background) {
      this.background=c.createBufferSource();this.background.buffer=this.ambience;this.background.loop=true;
      this.gain=c.createGain();this.gain.gain.setValueAtTime(0,c.currentTime);
      this.gain.gain.linearRampToValueAtTime(1,c.currentTime+.6);
      this.background.connect(this.gain).connect(c.destination);this.background.start();
    }
    if(this.voices.length>=4)this.voices.shift().stop();
    const voice=c.createBufferSource();voice.buffer=this.knock;voice.connect(c.destination);
    this.voices.push(voice);voice.onended=()=>{this.voices=this.voices.filter(v=>v!==voice);};voice.start();
    return c.state === "running";
  }
  close() {this.disposed=true;this.context?.close();this.voices=[];}
}
